name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
<<<<<<< HEAD
        scala: [2.13.8, 2.12.15]
=======
        scala: [2.13.4, 2.12.11]
>>>>>>> 5bc75c03c2d408d4bcad451fd5951c5614c96a96
        java: [adopt@1.8, adopt@1.11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: olafurpg/setup-scala@v11
        with:
          java-version: ${{ matrix.java }}
      - name: Run tests
        run: csbt ++${{ matrix.scala }} test